CHANGELOG.md, src/setup.py, src/simplipy/system.py
Hi there – there appears to be an issue with SimpliSafe wherein everyone's (or many people's) event logs are empty. This causes your library to throw an unhandled exception.
Since their "public API" isn't a real thing, this PR adds some very generic, very defensive `try/except` blocks that should catch this (and similar issues, should they ever occur).
=> Adding some defensive try/except blocks in case the SimpliSafe back-end blows up

README.md, simplipy/sensor.py, tests/test_sensor.py
Follow up to https://github.com/bachya/simplisafe-python/pull/8. This PR tries to make some more sense of what "triggered" looks like in V2 data. Tactically, there are two changes:
* Entry sensors will use the `entryStatus` property from the response data.
* Any other sensors will raise an exception (until we can determine how their triggered status is communicated via the API).
N/A
=> Re-architect triggered meaning for v2 sensors

simplipy/sensor.py, tests/fixtures/v2.py, tests/test_sensor.py, tests/test_system.py
This PR adds a `trigger_instantly` property for each sensor.
N/A
**Checklist:**
=> Added a `trigger_instantly` property to V2 and V3 systems

Makefile, README.md, simplipy/api.py, tests/test_system.py, tox.ini
This PR adds the ability to check the "dirtiness" of the refresh token (i.e., whether it has been changed or not). This allows applications that store refresh tokens to a filesystem, database, etc. to not constantly:
1. Read from the filesystem/DB
2. Determine whether the refresh token has changed
3. Save the new one to the filesystem/DB
Since the token won't change a large portion of the time, this is wasteful. Instead, at any point, library users can check for themselves:
```python
system.api.refresh_token_dirty
```
Note that this does create something of an [observer effect](https://en.wikipedia.org/wiki/Observer_effect_(physics)): by viewing the dirtiness property, we automatically reset it to `False`.
N/A …
=> Add dirtiness check for refresh token

README.md, example.py, simplipy/api.py, simplipy/system.py, tests/fixtures/__init__.py, tests/test_api.py, tests/test_system.py
"Standard" SimpliSafe accounts don't have the ability to get sensor values or set the state. Previously, this library threw an unhandled exception when these systems attempted these actions. This PR fixes that.
N/A
**Checklist:**
=> Fix a bug where unsupported features would throw unhandled exceptions

simplipy/api.py, tests/test_api.py
#19 was a bit too spammy with having `WARNING` level logs. This changes the notice to be `INFO` level.
N/A
**Checklist:**
=> Change unsupported feature log level to INFO

README.md, example.py, simplipy/api.py, simplipy/errors.py, tests/fixtures/__init__.py, tests/test_api.py
This PR adds a new exception for invalid credentials. It doesn't conflict with future `403` responses that might come from unavailable features.
N/A
**Checklist:**
=> Add error for bad initial credentials

simplipy/api.py
This PR adds a unique UUID to each API client. Previously, every client hardcoded the UUID; tactically, I _think_ this means that only one valid access token per client was issued.
N/A
**Checklist:**
=> Add unique UUID for each API client

simplipy/api.py, simplipy/errors.py
SimpliSafe access tokens last for 1 hour. When retrieving a new access token, `simplipy` sets the expiration timestamp to be the current time + 3600 seconds. This is cutting it too close: there is a small, but present risk that such a strategy will cause`simplipy` to see an access token as valid for 1 second too long. In these cases, a `RequestError` will be raised.
This PR fools `simplipy` into thinking that access tokens will expire 60 earlier. This should allow for plenty of buffer from the time they are created to their actual expiration.
Fixes https://github.com/bachya/simplisafe-python/issues/25
**Checklist:**
=> Make the access toke expire 60 seconds earlier

README.md, example.py, simplipy/api.py, tests/test_api.py, tests/test_sensor.py, tests/test_system.py
This PR removes the requirement of passing an `aiohttp.ClientSession` into the Client; that is now optional.
N/A
**Checklist:**
=> Make aiohttp.ClientSession optional

setup.py
aiodns is an optional dependency for aiohttp and it requires C compilation, which does not work on mac.
**Checklist:**
=> Remove aiodns from requirements

simplipy/api.py, tests/test_api.py
This PR slims up the logic that occurs when a `403` is detected.
N/A
**Checklist:**
=> Clean up 403 detection logic

simplipy/api.py, tests/test_api.py
It appears that every so often, SimpliSafe will invalidate an access token before its expiration time – who knows why. In that case, the user will continue to see `401` responses until that expiration time. This PR will attempt to refresh the access token upon seeing a `401` for the first time; if refreshing is unsuccessful and another `401` is seen, an `InvalidCredentialsError` exception is thrown.
N/A
**Checklist:**
=> Attempt refresh token upon initial 401

simplipy/system.py, tests/test_api.py
This PR moves all `system` updates to `asyncio` tasks. In addition to executing these tasks in parallel, this will make future updates easier.
N/A
**Checklist:**
=> Move system updates to asyncio tasks

README.md, example.py, simplipy/api.py, tests/test_api.py, tests/test_sensor.py, tests/test_system.py
Tradtionally, `api.get_systems()` returned a list of systems. There are several situations where it's preferable to lookup a particular system, instead; to make this fast, this PR changes the result of `api.get_systems()` to a dict with system ID as the key and `system` object as the value.
N/A
**Checklist:**
=> Make get_systems return a dict instead of a list

simplipy/system.py, tests/test_system.py
This PR fixes bugs with two edge cases when setting PINs:
* PINs that are anything other than 4 characters long
* PINs that are anything other than numeric
N/A
**Checklist:**
=> Fix edge cases when setting PINs

simplipy/sensor.py
This PR adds cameras as a valid sensor type. Note that it does not actually do anything _with_ cameras, camera streams, etc. – it just allows camera "types" to be recognized.
N/A
**Checklist:**
=> Add "camera" as a valid sensor type

AUTHORS.md, README.md
This pull request fixes multiple errors in the documentation.
Basically, I changed all `for system_id, system in systems:` into `for system_id, system in systems.items():` because Python doesn't like the first one.
Fixes https://github.com/bachya/simplisafe-python/issues/41
Because it's a documentation error, there were no tests written for it anyway, so I figured that it'd be the best to leave things how they were.
=> Fixes multiple lines of code with an added ".items()"

README.md, setup.py, simplipy/api.py, simplipy/sensor.py, simplipy/system.py, tests/fixtures/__init__.py, tests/fixtures/v2.py, tests/fixtures/v3.py, tests/test_api.py, tests/test_system.py
This PR drops runtime support for Python 3.5.3 and makes the minimum runtime version 3.6. One of a few benefits to follow: we now get to use f-strings.
N/A
**Checklist:**
=> Switch to f-strings (and remove support for Python 3.5.3)

.coveragerc, simplipy/api.py, simplipy/sensor.py, simplipy/system.py
Now that we can ensure a minimum of Python 3.6, we can use Python 3.6-style type annotations for variables.
N/A
**Checklist:**
=> Add Python 3.6-style variable type annotations

setup.py
Recently a `script` folder was added. Because of the way `setup.py` is set up, this was included in the published package, capturing the `script` namespace in Python when installed.
It broke running `hassfest` inside the Home Assistant repo.
=> Exclude scripts from published package

README.md, simplipy/__init__.py, simplipy/entity.py, simplipy/sensor.py, simplipy/system.py, tests/test_sensor.py
This PR splits out common sensor functionality into an `Entity` class. With support for locks on the horizon (https://github.com/bachya/simplisafe-python/issues/47), I want to start to demarcate between `Sensor` and `Lock` objects (even though they have a common ancestor).
N/A
**Checklist:**
=> Split common functionality into an Entity class

simplipy/entity.py, simplipy/system.py
This PR reworks how sensors are instantiated by putting more of the onus on the `System` object. This new architecture lays additional groundwork for eventually being able to support other types of SimpliSafe entities, like locks.
N/A
**Checklist:**
=> Re-work how sensors are instantiated

simplipy/entity.py, simplipy/sensor.py
This PR introduces a subclass of `Entity` called `EntityV3` – this provides common methods and attributes to all V3 entities, including sensors and (soon) locks.
N/A
**Checklist:**
=> Create concept of a V3 entity

example_locks.py, example_sensors_properties.py, example_setting_state.py, simplipy/api.py
In several places, I throw an `InvalidCredentialsError` without a message; this can lead to confusing log outputs. This PR makes those instances a little clearer.
N/A
**Checklist:**
=> Make InvalidCredentialsError instances more verbose

docs/index.rst, docs/lock.rst, docs/websocket.rst, pyproject.toml, scripts/get_events.py, scripts/test_websocket.py, simplipy/api.py, simplipy/errors.py, simplipy/websocket.py, tests/test_websocket.py
This PR adds experimental support for SimpliSafe's SocketIO-based websocket. Note that although the base functionality works, I cannot guarantee that this survives expired access tokens, etc.
Fixes https://github.com/bachya/simplisafe-python/issues/59
**Checklist:**
=> Add experimental support for SimpliSafe websocket

docs/lock.rst, docs/sensor.rst, simplipy/entity.py, simplipy/lock.py, simplipy/system/__init__.py, tests/test_lock.py
It's always been a tad awkward that sensors/locks couldn't request a state/property update – if you wanted to get the latest, you'd have to call `system.update()` (which updates _everything_ by default) and then go back to the sensor/lock. This PR adds an `update()` coroutine to all entities.
**Checklist:**
=> Give all entities an update() coroutine

docs/system.rst, simplipy/system/__init__.py, simplipy/system/v3.py, tests/test_system.py
This PR changes some private method names to be more consistent with the results they return.
N/A
**Checklist:**
=> Change generic "settings" call to be more specific

docs/api.rst, simplipy/system/v3.py, tests/fixtures/v3.py, tests/test_api.py, tests/test_system.py
This PR adds a new V3 system property (`chime_volume`) and several methods to set V3 properties on the system itself. Note that although some of this functionality is also available for V2 systems, I'm electing to not implement it at this time:
* At some point, I need to start focusing on the future, which is going to be with V3 systems.
* The V3 API is clearer on things like setting volumes; whereas its API payloads are easier to understand (`0` for `off`, `1` for `low`, etc.), the V2 API isn't clear at all (no `off`, `25` for `low`, `35` for `medium`, etc.).
I'll re-evaluate this as the need arises.
N/A
**Checklist:**
=> Add new property and property setter methods to V3 systems

simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py
In https://github.com/bachya/simplisafe-python/pull/69, I changed `system.update()` so that you could update system info, settings info, and sensor info independently. I did this by scheduling each API call as an `asyncio` task (for speed and concurrency); however, this introduced the possibility that the call to update sensor info would occur "too early" (a loose definition, as I'm not exactly sure _when_ that would be). In these cases, the SimpliSafe cloud would return an error:
```
Error requesting data from ss3/subscriptions/323864/sensors: 409, message='Conflict', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/323864/sensors?forceUpdate=true'
```
To address this possibility (and based on this [SO idea](https://stackoverflow.com/a/54670245)), …
=> Fix concurrency bug on system.update()

simplipy/entity.py
This PR adds doorbells as a valid sensor type. Note that it does not actually do anything _with_ doorbells, camera streams, etc. – it just allows doorbell "types" to be recognized.
N/A
**Checklist:**
=> Add "doorbell" as a valid sensor type

docs/api.rst, docs/system.rst, pyproject.toml, requirements_test.txt, simplipy/system/v3.py, tests/test_system.py
While experimenting with the various system property methods (`set_chime_volume`, etc.), I came to a realization: because SimpliSafe's cloud API anticipates receiving updated property values all at once, our method (sending properties one at a time) can result in failed updates if those calls happen too close together. So, this PR scraps those methods in favor of a single `set_properties` method that updates everything at once.
N/A
**Checklist:**
=> Consolidate system property methods into one

simplipy/sensor/v3.py
Apparently, not all sensors have the `instantTrigger` key in their settings; accessing one that doesn't exist throws an exception. This PR addresses that.
N/A
=> Address possibility of instant-trigger parameter missing

docs/api.rst, docs/websocket.rst, simplipy/websocket.py, tests/const.py, tests/test_websocket.py
This PR adds a helper method to get the "type" of a websocket event: `simplipy.websocket.get_event_type_from_payload`. It takes a single `dict` that should be the value returned to any function/coroutine registered with `simplipy.websocket.Websocket.on_event`.
The result will be one of:
* `armed_away`
* `armed_home`
* `arming`
* `automatic_test`
* `disarmed`
* `entry_detected`
* `sensor_error`
* `sensor_restored`
...and will log a warning (inviting the user to create an issue here) if the event type is unknown.
N/A
**Checklist:**
=> Add helper to determine websocket event types

simplipy/system/__init__.py, tests/test_system.py
`system.async_update()` executes multiple tasks in parallel. Until now, it swallowed exceptions and just logged errors. I realize that's bad: at the first sign of an error, it should re-raise that exception. This PR does that.
N/A
**Checklist:**
=> Don't swallow errors during update

simplipy/system/__init__.py, tests/test_system.py
`system.get_events()` previously had a `from_timestamp` parameter that took an int. I think it's more likely that people will want to pass a `datetime.datetime`, so this PR makes that change.
N/A
**Checklist:**
=> Change type of "from" parameter in system.get_events()

AUTHORS.md, simplipy/websocket.py, tests/test_websocket.py
This PR adds a more complete list of event types to the websocket API (including camera, doorbell, and lock events). Thatnks, @ssilence5 – this is why open source collaboration is amazing!
Fixes https://github.com/bachya/simplisafe-python/issues/87
**Checklist:**
=> Add additional websocket event types

docs/websocket.rst, simplipy/websocket.py
This PR adds support for identifying two additional websocket events:
* `sensor_not_responding`: occurs when a sensor can no longer be reached by the base station
* `sensor_restored`: occurs when a sensor is once again able to be reached by the base station
N/A
**Checklist:**
=> Add support for "Sensor Not Responding" and "Sensor Restored" events

docs/usage.rst, pyproject.toml
I want to begin using `dataclasses` where appropriate, which requires Python 3.7. So, this PR removes official support for Python 3.6.
N/A
**Checklist:**
=> Remove support for Python 3.6

docs/api.rst, docs/conf.py, docs/index.rst, docs/message.rst, docs/websocket.rst, examples/test_websocket.py, pyproject.toml, requirements_test.txt, simplipy/helpers/__init__.py, simplipy/helpers/message.py, simplipy/util/dt.py, simplipy/websocket.py, tests/helpers/__init__.py, tests/helpers/test_message.py, tests/test_websocket.py
Previously, the websocket's `async_on_event` and `on_event` callbacks gave the user raw data from the websocket. This put burden on the caller to know what to do with those results; with system notifications looking to use the same mechanism, this creates too much "loose" data. So, this PR alters `async_on_event` and `on_event` to return a `Message` dataclass.
N/A
**Checklist:**
=> Convert websocket events to a dataclass

script/release
This PR updates `script/release` to update the Sphinx version number (so that the version of the docs stays in line with the version of the PyPI package).
N/A
**Checklist:**
=> Update release script to bump docs version

docs/message.rst, docs/system.rst, simplipy/helpers/message.py, simplipy/system/__init__.py, tests/fixtures/v3_subscriptions_response.json, tests/test_system.py
This PR adds support for retrieving system messages and returning them as `Message` objects.
Fixes https://github.com/bachya/simplisafe-python/issues/90
**Checklist:**
=> Add support for retrieving system messages

simplipy/system/__init__.py
Previously, the logic for generate `Message` objects would execute anytime the `self.messages` property was utilized. This PR fixes that to only generate those objects when new data arrives.
N/A
**Checklist:**
=> Don't generate Message objects with each property inspection

.github/release-drafter.yml
This PR ensures that the release drafter GitHub action will categorize PRs with the `maintenance` label under the appropriate  heading.
N/A
**Checklist:**
=> Add "maintenance" label to release drafter

examples/test_websocket.py, simplipy/api.py, simplipy/websocket.py, tests/test_websocket.py
This PR updates the websocket to handle reconnection logic in the case of an updated access token. If the websocket is connected when the token updates, it will disconnect and reconnect.
N/A
**Checklist:**
=> Streamline websocket reconnections with new tokens

docs/advanced.rst, examples/test_sensor_properties.py, simplipy/api.py, tests/test_api.py, tests/test_system.py
The `refresh_token_dirty` property of the `API` object was too "automagical." This PR removes the concept entirely in favor of merely making the refresh token accessible through a property and relying on implementing libraries to do their own checks as to whether a refresh token is different from the one they have.
**Checklist:**
=> Remove refresh_token_dirty property from API object

simplipy/system/__init__.py
It appears that users with Standard monitoring plans don't see messages in the API; this can lead to an unhandled exception, which this PR addresses.
Note that this PR drops test coverage to 99%; given that I want to release a fix ASAP, going to push this forward now and will fix test coverage in a future PR.
N/A
**Checklist:**
=> Fix bug where Basic systems can't access notifications

simplipy/system/v3.py, tests/test_system.py
At times, the SimpliSafe cloud doesn't return base station status data (perhaps when it can't reach the base station? who knows). This leads to an unhandled exception, which this PR fixes.
This PR drops test coverage because it would be kludgy to add a test for it with the current framework. To get a fix out, I'm releasing it now and will fix coverage in a future PR.
N/A
**Checklist:**
=> Fix unhandled exception with V3 systems that are missing base station

examples/test_websocket.py, pyproject.toml, requirements_test.txt, simplipy/websocket.py, tests/test_websocket.py
The SimpliSafe websocket appears more fragile than I originally thought – at times, a "valid" request to close the connection will come and it will not recover.
This PR adds a watchdog: if it doesn't hear anything from the websocket in 5 minutes, it reconnects.
N/A
**Checklist:**
=> Websocket watchdog

simplipy/websocket.py
In my bleary, now-WFH-because-of-COVID-19 brain, I merged #135 with a way-too-low watchdown timeout manually hardcoded in. This PR fixes things by making the watchdog expire every 15 minutes.
N/A
**Checklist:**
=> Fix watchdog timeout bug

simplipy/system/__init__.py, tests/fixtures/events_empty_response.json, tests/fixtures/events_missing_response.json, tests/system/test_v3.py
It appears that the SimpliSafe cloud can sometimes fail to return event JSON (perhaps via an empty list _or_ via the `events` key missing altogether). This PR implements proper exception handling in such a case.
N/A
**Checklist:**
=> Fix bug where empty and/or missing events weren't handled correctly

simplipy/system/__init__.py, tests/system/test_v3.py
A triggered alarm was causing the system to report its state as `unknown` – this is because I had never actually tested a triggered alarm, so I had no definition for its state. 😆 This PR fixes that.
Fixes https://github.com/bachya/simplisafe-python/issues/145
**Checklist:**
=> Fix unknown state on triggered alarm

docs/advanced.rst, docs/system.rst, docs/usage.rst, docs/websocket.rst, examples/test_events.py, examples/test_locks.py, examples/test_sensor_properties.py, examples/test_sensor_types.py, examples/test_system_state.py, examples/test_websocket.py, simplipy/api.py, tests/sensor/__init__.py, tests/sensor/test_base.py, tests/sensor/test_v2.py, tests/sensor/test_v3.py, tests/system/test_base.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_api.py, tests/test_lock.py, tests/test_websocket.py
This PR makes the `aiohttp` `ClientSession` an optional parameter when creating an API object.
N/A
**Checklist:**
=> Make aiohttp ClientSession optional

simplipy/api.py, simplipy/system/__init__.py, simplipy/system/v3.py, tests/fixtures/subscriptions_missing_system_response.json, tests/system/test_v3.py
The SimpliSafe cloud can be flaky at times; often, the API doesn't return data that the system is using for its properties. Previously, accessing these properties would raise unhandled exceptions. This PR adds a guard that returns sensible default values for missing properties and logs appropriate warnings.
N/A
**Checklist:**
=> Guard system properties from missing data

pyproject.toml, requirements_test.txt
This PR unpins specific versions of `python-socketio` and `python-engineio` (and instead merely sets minimum required versions of those libraries).
Fixes https://github.com/bachya/simplisafe-python/issues/165
Fixes https://github.com/bachya/simplisafe-python/issues/166
**Checklist:**
=> Unpin specific versions of python-socketio and python-engineio

docs/advanced.rst, simplipy/api.py, simplipy/errors.py, tests/fixtures/unavailable_endpoint_response.json, tests/system/test_v3.py, tests/test_api.py
This PR adds a new exception type (`EndpointUnavailable`) that gets raised when the user attempts to call an endpoint that isn't available in their plan.
N/A
**Checklist:**
=> Add new exception type for when an endpoint isn't available in the current plan

.pre-commit-config.yaml, tests/async_mock.py, tests/test_websocket.py
This PR fixes the fact that `asynctest` no longer works in Python 3.8. The PR still ensures that it can be used for Python 3.6 and 3.7.
N/A
**Checklist:**
=> Handle asynctest not working in Python 3.8

simplipy/api.py, tests/test_api.py
A `403` response was raising a generic `RequestError`, rather than the more specific `InvalidCredentialsError`. This PR fixes that.
N/A
**Checklist:**
=> Fix bug where 403 didn't raise InvalidCredentialsError

docs/websocket.rst
This PR updates the websocket docs with the new event types added in https://github.com/bachya/simplisafe-python/pull/179 and makes the structure of the `WebsocketEvent` class clearer.
N/A
**Checklist:**
=> Update websocket docs

simplipy/system/__init__.py, simplipy/system/v3.py, tests/test_api.py
While diagnosing https://github.com/bachya/simplisafe-python/issues/184, I discovered that `system.update` was unintentionally throwing away exceptions that weren't based on `SimplipyError`. This could result in situations like valid `KeyErrors` that never show up; it also allowed a test to pass when it shouldn't. This PR cleans up that coroutine, fixes whatever issues it hid, and also handles https://github.com/bachya/simplisafe-python/issues/184.
Fixes https://github.com/bachya/simplisafe-python/issues/184
**Checklist:**
=> Fix hidden exceptions in system.update

simplipy/system/__init__.py
This PR follows up on https://github.com/bachya/simplisafe-python/pull/185 by ensuring that the existing system state is retained when the SimpliSafe cloud doesn't return a state value (which seems to be happening sporadically).
N/A
**Checklist:**
=> Keep existing system state when cloud fails to return a state

simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py
This PR splits up a too-large pin payload generation method into two variants appropriate to V2 and V3 systems, respectively.
**Checklist:**
=> Split up pin payload generation method

simplipy/system/__init__.py, simplipy/websocket.py
This PR removes some old/outdated `pylint` and `flake8` instructions.
**Checklist:**
=> Clean up old/outdated linting instructions

simplipy/system/v3.py
This PR fixes an erroneous default cooldown for V3 systems with locks (15 minutes vs. 15 seconds).
N/A
**Checklist:**
=> Fix incorrect V3 system cooldown units

requirements_test.txt, tests/test_websocket.py
This PR fixes tests that would be broken with the latest versions of `python-socketio` and `python-engineio` (which were not actively being used).
N/A
**Checklist:**
=> Fix tests with latest python-socketio and python-engineio

docs/advanced.rst, docs/system.rst, docs/usage.rst, simplipy/api.py, tests/system/test_base.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_api.py, tests/test_camera.py, tests/test_lock.py, tests/test_websocket.py
The previous manner for handling request retries (specifically, in the case of `401` responses) was fairly brittle and one-shot-ish. This PR puts an official request retry mechanism in place.
As a side effect, this should help uses who are currently getting bitten by the flakiness of SimpliSafe's cloud API and how, over the past several months, it can tend to return `409`/`500`/`502` responses during critical activities (like arming the alarm).
N/A
**Checklist:**
=> Overhaul request retry mechanism

simplipy/api.py
Following up on #222, this PR:
1. Fixes some incorrect logging during request retry
2. Removes a superfluous branch that couldn't be reached
N/A
**Checklist:**
=> Clean up retry logging and remove superfluous branch

simplipy/api.py, tests/test_api.py
After #222 and #223, I noticed this error in the Home Assistant logs every so often:
```
AttributeError: 'str' object has no attribute 'get'
```
I realized that when SimpliSafe returns a 401 response, I gives an escaped-string response body:
```
HTTP/1.1 401 Unauthorized
Date: Tue, 02 Mar 2021 04:59:01 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 14
Connection: close
...
"Unauthorized"
```
Because the body is an escaped string, it is technically valid JSON and was therefore skipping the logic designed to catch non-JSON responses. This PR fixes the issue and updates the tests to ensure we properly test what a 401 response _actually_ looks like.
N/A
**Checklist:**
=> Fix bug with refreshing 401

simplipy/api.py
The `RequestError` thrown when all request retries expire showed incorrect verbiage (the number of total retries was one too many). This PR fixes that verbiage.
N/A
**Checklist:**
=> Fix incorrect exception error verbiage

examples/test_pins.py, simplipy/system/v2.py, simplipy/system/v3.py
Recently, attempting to set a PIN resulted in this `DEBUG`-level log message:
```
DEBUG:simplipy:Data received from /ss3/subscriptions/XXXXXX/settings/pins: {'type': 'PinError', 'message': 'You must have at least 4 user pins', 'code': '206', 'statusCode': 400, 'props': {}}
```
Some investigation revealed that SimpliSafe changed the request payload to set PINs in v3 systems. This PR makes the appropriate update.
Fixes https://github.com/bachya/simplisafe-python/issues/228
**Checklist:**
=> Fix bug with setting PINs in v3 systems

docs/advanced.rst, docs/usage.rst, simplipy/api.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_api.py
Because the SimpliSafe refresh token can sometimes fail for no apparent reason, I'm realizing that we shouldn't expose it (or any methods for using it) to the user; instead, we should handle all forms of reauthentication (refresh token, full-on credentials) underneath the hood.
This PR takes the first step by making any references to the refresh token private; it also removes the `API.login_via_token` method.
N/A
**Checklist:**
=> Make references to refresh token private

docs/system.rst, docs/usage.rst, examples/test_events.py, examples/test_locks.py, examples/test_pins.py, examples/test_sensor_properties.py, examples/test_sensor_types.py, examples/test_system_state.py, script/mfa, simplipy/__init__.py, simplipy/api.py, tests/sensor/__init__.py, tests/sensor/test_base.py, tests/sensor/test_v2.py, tests/sensor/test_v3.py, tests/system/test_base.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_api.py, tests/test_camera.py, tests/test_lock.py
Following up on #240, this PR continues towards handling all refresh token/reauth logic internally by reworking how to retrieve an authenticated API object (via `simplypi.api.get_api`).
N/A
**Checklist:**
=> Rework getting an authenticated API object

simplipy/api.py
#243 introduced the ability for the `API` object to automatically reauthenticate itself when its refresh token fails, but in both cases, an `InvalidCredentials` exception would still be raised. This PR fixes that.
N/A
**Checklist:**
=> Fix bug where token refresh and reauth would both erroneously raise an

simplipy/api.py, simplipy/lock.py
In certain cases (like with locking/unlocking a lock), the API will return a null payload (with just a successful HTTP response code). This PR protects against unhandled exceptions that might be caused by assuming otherwise.
N/A
**Checklist:**
=> Protect against null response payloads

.github/workflows/ci.yaml, .pre-commit-config.yaml, docs/usage.rst, pyproject.toml, simplipy/api.py, simplipy/device/__init__.py, simplipy/device/camera.py, simplipy/device/sensor/__init__.py, simplipy/device/sensor/v3.py, simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py
This PR removes official support for Python 3.7. Since my primary goal is supporting Home Assistant and they maintain compatibility with the two most recent Python versions, I aim to do the same.
**Checklist:**
=> Remove official support for Python 3.7

docs/lock.rst, docs/sensor.rst, docs/system.rst, docs/usage.rst, examples/test_client_by_auth.py, examples/test_client_by_refresh_token.py, examples/test_websocket.py, simplipy/api.py, simplipy/device/__init__.py, simplipy/device/lock.py, simplipy/device/sensor/v2.py, simplipy/device/sensor/v3.py, simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py, simplipy/websocket.py, tests/sensor/test_base.py, tests/sensor/test_v2.py, tests/sensor/test_v3.py, tests/system/test_base.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_api.py, tests/test_camera.py, tests/test_lock.py
**Breaking Change**
Coroutines now start with `async_`.
As a best practice, this PR modifies coroutines to start with `async_` (so as to easily delineate them).
**Checklist:**
=> Add `async_` prefix to all coroutine definitions

docs/api.rst, docs/usage.rst, pyproject.toml
It turns out that my instructions for getting the auth code were Safari-specific. This PR adds some more information for other browsers.
N/A
**Checklist:**
=> Add more specific browser information to Authentication docs

simplipy/system/v3.py
This PR uses some already-defined constants (rather than defining new strings) in the V3 system properties map.
N/A
**Checklist:**
=> Use V3 system properties constants

simplipy/system/v3.py
This PR implements constants for numeric V3 system property limits (so that other libraries can just import them, rather than having to know about them).
N/A
**Checklist:**
=> Use constants for V3 system properties that have numeric values

docs/system.rst, simplipy/system/v3.py, tests/system/test_v3.py
Previously, V3 volume values were stored as constants. This doesn't really jive with the rest of the library, where a constrained set of values are placed in enums. This PR moves volume levels into a single enum.
N/A
**Checklist:**
=> Use enum for V3 volume property values

docs/lock.rst, docs/sensor.rst, docs/system.rst, pyproject.toml, simplipy/device/__init__.py, simplipy/device/lock.py, simplipy/device/sensor/v2.py, simplipy/device/sensor/v3.py, simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py, tests/sensor/test_base.py, tests/system/test_base.py, tests/system/test_v2.py, tests/system/test_v3.py, tests/test_lock.py, tests/test_websocket.py
Enum values are really supposed to be uppercase (since, in a way, they represent constants), so this PR standardizes all enums this way.
N/A
**Checklist:**
=> Make all enum values uppercase

simplipy/system/__init__.py
This PR properly wraps a decorator that was messing up Sphinx's autodoc.
N/A
**Checklist:**
=> Wrap guard_from_missing_decorator to fix autodoc

simplipy/system/v3.py, tests/system/test_v3.py
https://github.com/bachya/simplisafe-python/pull/287 introduce the `Volume` enum for V3 systems, but didn't go far enough to actually store volume levels _as_ values from this enum. This PR fixes that.
**Checklist:**
=> Store V3 system volumes as `Volume` enums

docs/api.rst, docs/websocket.rst, simplipy/api.py, simplipy/util/__init__.py, simplipy/websocket.py, tests/test_api.py, tests/test_websocket.py
This PR does a couple things re: callbacks:
* Centralizes the logic in `simplipy.util`
* Enables refresh token callbacks to be synchronous functions *or* coroutines
* Changes method names/verbiage/etc. that previously referred to `listener` to now refer to `callback` (to standardize the language)
N/A
**Checklist:**
=> Centralize and standardize callback usage

simplipy/websocket.py, tests/conftest.py, tests/test_websocket.py
From looking at Home Assistant logs, it's apparent that the SimpliSafe websocket, like the REST API, is a little flaky. This leads the current websocket implementation to connect/disconnect too many times, trigger the watchdog spuriously, etc. So, this PR adds some guards:
1. `async_connect` only attempts to connect if we aren't already connected.
2. Same with `async_disconnect`.
3. We only trigger the watchdog if its underlying task hasn't already been cancelled.
**Checklist:**
=> Add appropriate guards to websocket actions

simplipy/websocket.py
The websocket watchdog wasn't properly canceling when we disconnected from the websocket. This could create an unnecessary loop of the watchdog triggering. This PR fixes things.
N/A
**Checklist:**
=> Fix websocket watchdog not canceling when websocket disconnects

simplipy/api.py
My logic for storing the access token's expiration datetime (appropriately padded) was incorrect. This could result in multiple successful (but unnecessary) requests to refresh the access token if those requests are within microseconds of each other. This PR fixes the logic.
N.A
**Checklist:**
=> Fix incorrect padding in the access token expiration datetime

simplipy/api.py, simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py
https://github.com/bachya/simplisafe-python/pull/263 failed to incorporate the `API` object's `request` method. This PR makes things consistent by renaming that method to `async_request`.
N/A
**Checklist:**
=> Ensure API request method is consistently named

simplipy/api.py, tests/test_api.py
This PR adds two new methods to the API object:
* `disable_request_retries()`
* `enable_request_retries()`
N/A
**Checklist:**
=> Add ability to disable and enable retry logic

simplipy/device/camera.py, tests/test_camera.py
This PR transitions camera types from constants to the `DeviceTypes` enum (to be more consistent with the rest of the library).
N/A
**Checklist:**
=> Move camera type from constants to CameraTypes enum

simplipy/system/__init__.py, simplipy/system/v2.py, simplipy/system/v3.py, tests/system/test_v2.py, tests/system/test_v3.py
It looks like clearing notifications on V3 systems has a new endpoint; this PR adds it.
N/A
**Checklist:**
=> Fix bug where V3 systems couldn't clear notifications

simplipy/api.py, simplipy/websocket.py, tests/system/test_v3.py, tests/test_api.py, tests/test_lock.py, tests/test_websocket.py
The current method for refreshing access tokens when receiving an `HTTP 401` or `HTTP 403` assumed that tokens will always last 1 hour. I realize that, given some flakiness in the API, this isn't a safe assumption: we need to refresh _whenever_ we receive those codes.
This PR makes the appropriate adjustments and assumes that concurrent `401`s/`403`s within a 5-second window of a successful token refresh should be ignored.
N/A
**Checklist:**
=> Fix bug with how 401s are caught and refreshed

simplipy/api.py, tests/system/test_v3.py, tests/test_api.py, tests/test_lock.py
#301 had the refresh token window detection logic backwards. This PR fixes things.
N/A
**Checklist:**
=> Fix incorrect refresh token window logic

simplipy/api.py
`add_refresh_token_callback` can take coroutine functions, but the typing is too restrictive. This PR fixes things.
N/A
**Checklist:**
=> Fix instance of too-strict typing

simplipy/api.py, tests/system/test_base.py
We were detecting a subscription's "active" status incorrectly. This PR fixes the bug.
N/A
**Checklist:**
=> Fix bug in how subscription status is determined

simplipy/api.py, tests/test_api.py
This PR ensures that `async_from_auth` and `async_from_refresh_token` wrap any exception that might occur.
N/A
**Checklist:**
=> Wrap more exceptions when instantiating an API client

.pre-commit-config.yaml, pyproject.toml, requirements_test.txt
This PR loosens the dependency pinning for `voluptuous`. It tangentially updates the version of `black` used in `pre-commit` to resolve conflicts.
Fixes https://github.com/bachya/simplisafe-python/issues/318
**Checklist:**
=> Loosen dependency pin for voluptuous

pyproject.toml
Remove docutils dependency.
If needed, then it should be either in dev-dependencies, or only in a requirements file for CI
Related to https://github.com/home-assistant/core/pull/68897
**Checklist:**
=> Remove docutils dependency

simplipy/util/__init__.py
We can handle sync callbacks without using `asyncio`.
**Checklist:**
=> Simplify sync callback handling

simplipy/api.py, tests/test_api.py
Sometimes, the SimpliSafe API will reject a connection, have a DNS issue, etc. We don't currently handle these when creating an API client. This PR adjusts things to wrap them in the appropriate `simplisafe-python` exception so that users can retry.
N/A
**Checklist:**
=> Handle more errors during API creation process

simplipy/api.py
We were storing the login verification URL when already logged in as a string. This would raise an exception later on.
Fixes #337 
**Checklist:**
=> Properly store already-logged-in verification URL

docs/usage.md, simplipy/api.py
This PR adds a public method to the `API` object that allows users to initiate the token refresh process themselves.
Fixes https://github.com/bachya/simplisafe-python/issues/355
**Checklist:**
=> Provide a method to manually refresh tokens

.readthedocs.yml
When we transitioned dependencies to pure Poetry, it broke Read the Docs and I never knew about it. This is an attempt to fix.
N/A
**Checklist:**
=> Update Read the Docs to work with Poetry

.github/workflows/ci.yaml, docs/usage.md, pyproject.toml
In preparation for Python 3.11's release on 10/24, this PR adds 3.11.0rc2 to CI so we can begin testing the library against it. Regular reminder that we support the three most recent versions, so when 3.11 is officially released, we will remove "official" support for 3.8.
N/A
**Checklist:**
=> Add preliminary support for Python 3.11

simplipy/api.py, tests/system/test_base.py
https://github.com/home-assistant/core/issues/82875 showed us that the current method of determining whether a subscription is active is invalid. This PR changes how we do that detection to (hopefully) be more consistent.
N/A
**Checklist:**
=> Change how inactive systems are detected

simplipy/system/__init__.py
Guarding these properties produces a typing nightmare when implementing. We should reasonably expect these properties to exist.
N/A
**Checklist:**
=> Don't guard system ID or serial against missing data

simplipy/api.py, tests/system/test_base.py
This follows up on https://github.com/bachya/simplisafe-python/pull/383. Per https://github.com/home-assistant/core/issues/83494, this problem is more challenging than anticipated because it's unclear which data key from the SimpliSafe API equates to "active."
This PR takes a different stab at using a data key—`hasBaseStation`— that seems to be consistently `False` when a subscription is inactive (regardless of what subscription type is used).
N/A
**Checklist:**
=> Take another stab at detecting inactive subscriptions

docs/usage.md
It's apparently very tricky to find the code in non-Chromium browsers (like Safari or Firefox). This PR adds docs encouraging the use of a Chromium-based browser.
N/A
**Checklist:**
=> Add documentation about Chromium-based browsers
