CHANGELOG.md
src/setup.py
src/simplipy/system.py

Simplisafe is returning "error" for status in a "Locations" request.  This changes gets the status from the "Dashboard" request.

Status Unknown Fix

---

Makefile
README.md
tox.ini

This PR makes typing a `Makefile` command and adds a suggestion to `README.md` regarding its usage.

Made typing a Makefile command

---

simplipy/system.py

This PR adds support for an `error` system state and does a better job of handling unknown states.
N/A
**Checklist:**

Add support for `error` state and better unknown state handling

---

example.py
simplipy/api.py
simplipy/system.py

This PR adds better `logging` support for easier debugging.
N/A
**Checklist:**

Add better logging

---

README.md
simplipy/system.py
tests/fixtures/v3.py
tests/test_api.py
tests/test_system.py

This PR adds several new V3 system properties that are updated with each call to `system.update`:
* `alarm_duration`
* `alarm_volume`
* `battery_backup_power_level`
* `entry_delay_away`
* `entry_delay_home`
* `exit_delay_away`
* `exit_delay_home`
* `gsm_strength`
* `light is True`
* `rf_jamming is False`
* `voice_prompt_volume`
* `wall_power_level`
* `wifi_ssid`
* `wifi_strength`
N/A
**Checklist:**

Add several new V3 properties

---

README.md
simplipy/api.py
simplipy/errors.py
simplipy/system.py
tests/fixtures/v2.py
tests/fixtures/v3.py
tests/test_system.py

This PR adds functionality to get, set, reset, and remove PINs. This opens up all sorts of possibilities by adding/changing/removing PINs on the fly.
N/A
**Checklist:**

Add support for PINs

---

README.md
simplipy/system.py
tests/fixtures/__init__.py
tests/test_system.py

This PR adds a convenience method to get the latest system event.
N/A
**Checklist:**

Add get_latest_event() system method

---

.travis.yml
pyproject.toml

This PR uses poetry to install all dependencies for CI (cleaner).
N/A
**Checklist:**

Use poetry to install all dependencies in CI

---

simplipy/sensor/v2.py
simplipy/sensor/v3.py
simplipy/system/__init__.py

Following up on https://github.com/bachya/simplisafe-python/pull/63, this PR performs a similar move and breaks `sensor.py` up into multiple files.
N/A
**Checklist:**

Break sensor.py into multiple files

---

docs/api.rst
docs/conf.py
simplipy/api.py
simplipy/entity.py
simplipy/errors.py
simplipy/lock.py
simplipy/sensor/v2.py
simplipy/sensor/v3.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py
simplipy/websocket.py
tests/test_system.py

This PR adds robust docstrings to all classes/methods/etc. for documentation purposes.
N/A
**Checklist:**

Add Sphinx-style docstrings to all methods for docs

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
Makefile

This PR adds another GitHub Action – `Create & Publish a Release` – that looks for new tags and publishes releases/packages from them.
N/A
**Checklist:**

Add GitHub Action to create and publish a release

---

script/release

This PR adds `script/release` to automate the creation of a tagged release commit (which, when pushed here, will trigger the job to publish to PyPI). Automation! 🙌 
N/A
**Checklist:**

Add release script

---

.github/workflows/ci.yaml
script/release

Now that functionality has been moved to shell scripts, we should add `shellcheck` to CI. FYI, it's currently too clunky to get it working in `pre-commit`.
N/A
**Checklist:**

Add shellcheck to CI

---

.github/workflows/ci.yaml
docs/system.rst

This PR consolidates all `pre-commit` commands into one in CI.
N/A
**Checklist:**

Consolidate pre-commit commands in CI

---

tests/fixtures/v3_subscriptions_unknown_state_response.json
tests/test_system.py

This PR fleshes out a too-simplistic test.
N/A
**Checklist:**

Fix simplistic system state test

---

docs/system.rst
simplipy/websocket.py
tests/test_websocket.py

This PR fixes an inconsistent websocket event property name.
N/A
**Checklist:**

Fix incorrect websocket event property name

---

docs/lock.rst

Fixes a small typo in the lock docs
No
**Checklist:**
- [NA] Confirm that one or more new tests are written for the new functionality.
- [NA] Update `README.md` with any new documentation.
- [NA (already was added)] Add yourself to `AUTHORS.md`.

Fix typo in the lock docs

---

docs/system.rst

This PR fixes an incorrect `system.get_events()` example.
N/A
**Checklist:**

Fix an error in the system docs

---

tests/system/test_v3.py

This PR properly uses `pytext` fixture parametrization to avoid an extra, unnecessary API call.
N/A
**Checklist:**

Properly parametrize V3 system test

---

tests/system/test_v2.py
tests/test_api.py

This PR fixes various linting and documentation issues within several tests.
N/A
**Checklist:**

Fix various test linting and documentation issues

---

simplipy/websocket.py

Previously, _any_ disconnection event from the websocket would kill the watchdog; not good. This PR updates things so that only a user-initiated websocket disconnect kills the watchdog.
N/A
**Checklist:**

Fix bug where any websocket disconnection kills the watchdog forever

---

README.md

Fixes the documentation.
Nope. Just fixes getting started with the project.

Fix bug in documentation

---

docs/conf.py

Runs black formatting
No
**Checklist:**

Apply black formatting to Sphinx config file

---

.github/stale.yml

Add help wanted to exempt labels for stale bot
No
**Checklist:**

Add help wanted to exempt labels

---

simplipy/system/__init__.py

This PR adds support for a system state of `test`.
https://github.com/bachya/simplisafe-python/issues/178
**Checklist:**

Add "test" system state

---

simplipy/api.py

This PR cleans up the API module:
* Cleaner variable names
* Reduction in unnecessary API properties
* Clearer method names
* Clearer inline documentation
**Checklist:**

Clean up API module

---

simplipy/api.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py

This PR cleans up system creation to be more explicit and easier to read.
**Checklist:**

Clean up system creation

---

simplipy/api.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py

This PR removes some redundant and unnecessary debug-level logging statements.
N/A
**Checklist:**

Remove unnecessary logging statements

---

simplipy/camera.py
simplipy/entity/factory.py
simplipy/system/__init__.py
simplipy/system/v3.py
simplipy/websocket.py

This PR removes additional unnecessary type annotations.
N/A
**Checklist:**

Remove unnecessary type annotations

---

simplipy/system/v2.py
simplipy/system/v3.py

This PR replaces a few instances of an `Enum` type annotation with a more specific type  (in this case, `SystemStates`).
N/A
**Checklist:**

Replace Enum type annotations with SystemStates

---

simplipy/api.py
simplipy/camera.py
simplipy/const.py
simplipy/entity/__init__.py
simplipy/entity/factory.py
simplipy/lock.py
simplipy/sensor/v2.py
simplipy/sensor/v3.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py
simplipy/websocket.py

This PR abstracts a single logger into a constant (so that we don't redefine the same thing everywhere).
N/A
**Checklist:**

Abstract logger into a constant

---

script/mfa

This PR changes the MFA script's log level from `DEBUG` to `INFO`.
N/A
**Checklist:**

Change MFA script to use INFO-level logging

---

simplipy/api.py
simplipy/entity/__init__.py
simplipy/lock.py
simplipy/sensor/v2.py
simplipy/sensor/v3.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py
tests/test_lock.py

https://github.com/bachya/simplisafe-python/pull/193 instituted a bug where data was not properly passed from internal storage to the entities that need it (causing entity attributes to be incorrect). This PR fixes that issue. It also cleans up system initialization logic.
N/A
**Checklist:**

Fix bug with data references

---

simplipy/camera.py

This PR fixes incorrect data reference sharing for cameras.
N/A
**Checklist:**

Fix data references for cameras

---

simplipy/system/v3.py

This PR simplifies how camera objects are set up in V3 systems (and makes the process consistent with all systems' post-init process).
**Checklist:**

Simplify camera object setup

---

simplipy/system/__init__.py

This PR removes an unnecessary encapsulation for updating system data.
N/A
**Checklist:**

Remove redundant system update method

---

simplipy/system/v3.py

This PR fixes a coroutine that wasn't properly `await`ed.
N/A
**Checklist:**

Properly await coroutine

---

.github/workflows/ci.yaml
docs/usage.rst
pyproject.toml

This PR officially adds support for Python 3.9.
N/A
**Checklist:**

Add support for Python 3.9

---

simplipy/system/v3.py
tests/system/test_v3.py

As reported elsewhere ([Reddit](https://www.reddit.com/r/simplisafe/comments/f80abl/simplilock_not_responding_message/fwuo3k0)), users with locks are reporting that sporadically, they are hearing "Warning: XYZ lock not responding" messages from their base stations with libraries that use the unofficial cloud API. It appears that due to a bug in that API, attempting to update these systems too soon after arming/disarming the system results in some sort of conflicting state, which may cause this issue.
Based on the success of [the SimpliSafe `homebridge` plugin's efforts](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/134), this PR enforces a "cooldown" of sorts after arming/disarming the system: if the user attempts to update the …

Work around SimpliSafe issue re: system state, updating, and locks

---

simplipy/api.py

This PR fixes a bug wherein the "did we retry a 401 request?" property was never properly reset.
N/A
**Checklist:**

Ensure 401 retry clears properly

---

simplipy/system/__init__.py

This PR fixes some `pylint` warnings about explicit re-raises.
N/A
**Checklist:**

Fix some pylint warnings

---

simplipy/api.py

This PR reworks the API retry code to make it clearer when it should break out of the retry loop.
N/A
**Checklist:**

Make API retry break clearer

---

docs/api.rst

This PR fixes missing `simplipy.api` documentation
N/A
**Checklist:**

Fix documentation of simplipy.api

---

simplipy/api.py
simplipy/errors.py
tests/system/test_v3.py
tests/test_api.py
tests/test_camera.py

I've had some more time to learn about `backoff`, so this PR cleans up my implementation of it.
N/A
**Checklist:**

Clean up backoff implementation

---

simplipy/websocket.py
tests/test_websocket.py

I published https://github.com/bachya/simplisafe-python/pull/259 a bit too quickly, as the ability to have sync _and_ async functions as websocket listeners wasn't implemented! This PR "fixes" things.
N/A
**Checklist:**

Fix bugs with providing coroutines as websocket listeners

---

simplipy/system/__init__.py

This PR removes some no-longer-used system constants.
N/A
**Checklist:**

Remove unused system constants

---

docs/usage.rst

This PR updates SimpliSafe plan information in the usage docs.
N/A
**Checklist:**

Update plan info in the usage docs

---

docs/advanced.rst
docs/system.rst
docs/usage.rst
docs/websocket.rst

This PR makes some documentation updates to more clearly explain how the refresh token is to be used.
N/A
**Checklist:**

Update usage docs

---

pyproject.toml
requirements_test.txt

This PR loosens the version pinning of `pytz`.
Fixes https://github.com/bachya/simplisafe-python/issues/316
**Checklist:**

Loosen version pinning on pytz

---

pyproject.toml

Not strictly required, but maybe makes it easier for the future?
**Checklist:**

Loosen websockets dependency

---

examples/test_client_by_credentials.py
pyproject.toml
requirements_test.txt
simplipy/api.py
tests/conftest.py
tests/test_2fa.py
tests/test_api.py

We had the sequencing for email-based 2FA incorrect (chalk it up to not having an account to test with). This PR fixes things.
N/A
**Checklist:**

Fix incorrect sequencing for email-based 2FA

---

docs/usage.rst

This PR fixes some broken English in the docs.
**Checklist:**

Fix incorrect docs

---

docs/conf.py
docs/usage.rst
simplipy/api.py

This PR updates some other documentation issues I found. It also makes the copyright date dynamic.
N/A
**Checklist:**

Fix more doc issues

---

.pre-commit-config.yaml
simplipy/device/lock.py
simplipy/system/__init__.py
simplipy/system/v3.py

This PR adds the [`pyupgrade`](https://github.com/asottile/pyupgrade) pre-commit hook to help us take advantage of new Python features depending on what versions we support.
N/A
**Checklist:**

Add pyupgrade pre-commit hook

---

pyproject.toml
tests/conftest.py

This PR cleans up some `pytest` warnings.
N/A
**Checklist:**

Clean up pytest warnings

---

docs/camera.md

Fixes https://github.com/bachya/simplisafe-python/issues/366
**Checklist:**

Fix inconsistency in camera docs

---

.pre-commit-config.yaml
docs/conf.py
tests/test_websocket.py

This PR updates all pre-commit hooks to their latest versions.
N/A
**Checklist:**

Update all pre-commit hooks

---

docs/usage.md

The steps were numbered wrong.
N/A
**Checklist:**

Fix small auth docs mistake

---

.github/release-drafter.yml
README.md

This PR adjusts the code coverage badge to track the `dev` branch (and not `main`).
N/A
**Checklist:**

 Change the coverage badge to track the `dev` branch

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
.pre-commit-config.yaml
docs/usage.md
pyproject.toml
simplipy/system/__init__.py
simplipy/system/v3.py

Happy Python 3.11 release day! This PR updates CI to tests against the GA release. Per our standards of supporting the three most recent versions, this PR also removes official support for anything before 3.9.
N/A
**Checklist:**

Update CI to use GA release of Python 3.11

---

AUTHORS.md

Shortens my name in AUTHORS.md for the sake of privacy
No
**Checklist:**
NA

Remove full name

---

.readthedocs.yml
poetry.lock
pyproject.toml

Our process for building readthedocs broke at some point. This PR fixes things.
N/A
**Checklist:**

Fix RTD builds

---

simplipy/device/__init__.py
simplipy/system/__init__.py
simplipy/system/v2.py
simplipy/system/v3.py

SSIA. The old location didn't make sense.
N/A
**Checklist:**

Relocate `get_device_type_from_data` to `simplipy.device`

---

simplipy/device/__init__.py
simplipy/device/sensor/v3.py
tests/fixtures/v3_sensors_response.json
tests/system/test_v3.py

SSIA
Fixes https://github.com/bachya/simplisafe-python/issues/515
**Checklist:**

Add support for Smoke+CO Detector

---

simplipy/device/__init__.py
simplipy/device/sensor/v3.py

SSIA
Fixes https://github.com/bachya/simplisafe-python/issues/538
**Checklist:**

Add support for v2 Motion Sensor

---

docs/usage.md

SSIA
Fixes https://github.com/bachya/simplisafe-python/issues/597
**Checklist:**

Fix incorrect API instantiation docs

---

simplipy/device/__init__.py

Add device mapping for indoor camera

---

README.md

Fix incorrect `pytest` command in README

---

poetry.lock
pyproject.toml

We no longer use it.
N/A
**Checklist:**

Remove `beautifulsoup4` as a dependency
